[package]
name = "dataguard-reports"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = "0.4.42"
dataguard-core = { path = "../dataguard-core/" }
serde = { workspace = true }
serde_json = "1.0.145"

[lints]
workspace = true
