[package]
name = "dataguard-reports"
version.workspace = true
edition.workspace = true

[dependencies]
dataguard-core = { path = "../dataguard-core/" }
serde = { workspace = true }

[lints]
workspace = true
